### ISSUE TITLE
There are no tests

### ISSUE THREAD

**Issue by arjunblj** [vm/shlack#4]
Pls let me know if I can be of assistance. I only use software with high test coverage. 

http://www.cs.northwestern.edu/~ddowney/courses/111_Winter2011/design_recipe_example.html

![](https://c2.staticflickr.com/6/5056/5516878964_dbff7851fe_z.jpg)

**Comment by vm** [comment]
Tests are definitely important. Got carried away with Rust's error handling. If you'd like to add some examples as tests that would be great!
